apiVersion: v1
kind: Secret
metadata:
    name: isponsorblocktv-secret
stringData:
    config.json: ENC[AES256_GCM,data:MGwOUcq0knbjH+MdZWp+cQM6fmdtW1ReMRhG6IeTaH7PgwUwoGxa2ES/lEx/xgJgchwahc74/B0Rq1HVsHti8KAt3HJ6Oha7kstg4C+VslwjJoavreRebawFyZb/YuHxaNcJSh8ItTek8RA8BuyvqGhZhn6xlSrbJw5gNUF2oqosXGcUtVhGqUrBXLy6ZoUPk7FItrPcazrJNxfnoTRtK+0vTJbtApQJuXC9wxlIH2cdUakHvwgcMksvWK2YAjilxSJRDnZJ+VwlJLtziZXuH9MlBYSaUOziLFuuoRvgU3leFmeU6Ht/waRNNVGv1h7p8l7fVhDxgPjPdDJZN3vO+OHM95C5wbejcgmDZmv4M1V2MjpFWIqdXPjP8/6B1RJbxjQh/LI/fQnu23rudAlEwtwgNLyChiPxTeVuLGKWBYT9N4WvElVUiURx+z3scncFfnitmOFGOEePeUqFDDgaAZYIc3nBWst8oYH1ooUFHRS56odvRcL0nYYcc+B2AxrybHXqahccSZDADKZXdMYzqiAFbxQykOPQ8DHUWZ7CbBw7oxEIFei8PtQGnKz7Q74IaolSj9ZRP6pxhsUE9rEcU0BLj5qT14EaK309H1ZTURjnBDwLr1LCShdBflusBJ8tK4gAHzWeawpXfYc0JN/kQZF6X0QXkx3j0n2LZ45Y5LWyEPmAl5RMXEuRE11cNxzxbbaAkI8Dde12vcCNfb1iJX7bYI+Oy6fuHvi9jsuPH9JCrHmZPj3K6N7YAq1pM5Q+SS/ePJgWeftit8wejEiXRMUu5GB8wphws2ckqbSaucWGwUicwMQ7hwe3n9Esf2lOr786mrio0V0Cvu8gOCrpnC9a0ktUxBzFBwR5KA1HezPK9agqpSBINZEpf4Jyo8J7ASb6e+cY7be8U+GfnTyGdp6DdUfIhb4lJZ7V04JTmCnQGAGFt6N8CVwhDV9DCJ80GE97ExZ49svTc2vpkT8RZBoA9DLFfI/m2qPjZDuf3saqButYLbCo3i50WG16aTiELXN+fTyFDYz88QAkhW+dgL8hWUlmiOMJ40+iEFIgfXzLVDrFtEp5DCVOFPdMLPcjJo8qv/CsnQzR8LwgGIDpc1RwHe3KiHej6uew1Mt+5VlZkzGTNgb8lc+XnJy4qeg7m9gLTFaAatPLm0WUaQ7y+tV8xrEyI1P4bvP09KxKOo83XGqPVCeEeLz1xVDMxk9uX0HWSYf1,iv:rqq5alCBJbKp2w4alQTLN2zZ/St8bBC3k0xGA8ZxC4I=,tag:HfGC20thWweuvBu2OV4bmA==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUL1l3TzEzcGFRdGN0RHA2
            aG84MFJHZXdRQWQxcXdrZ08yM21KZlpiYTNVCm1IeVAydXNBSGcyZGNDa1JEVnNE
            VlgwaUJCYkFSMjhPVmNlKzJJUHpZbzAKLS0tIG83L28rUGtTNmVwZ1hkWDY3REoy
            Nno5Q2dLT0JwVlVvTHJCVzBKNm9qM2MKbEUdrfTQbkitTFqDJCq/HxYoOjmLKB9u
            oaOaLfVHhsgGv3FIG7ppDCpM3Aiw6kbz7W6LCCfiVs3DXiXwQ2wJ0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-28T15:47:16Z"
    mac: ENC[AES256_GCM,data:mfeyVpnaI5h0x1wS9A0H6Ee+2xWI/1lWhNbzcVdPEXVfhLa36aIv8s18kTLV1Qs7V6TnCsRmLWj3UwjPykD6fq7BYvb00t4HEvL0RzARm3SEcCYHbqs0eSpG07THpeer+tKxGgwwnGsGHg4L3H9CYSJ8KNKSDsy199TU6M7wp7Y=,iv:/lKzFmulCyMVc+AZyyJTTNQRa5I/7Q46yWrNrr1W8dQ=,tag:y36uurcFDkDILRLJeHX7Iw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
