apiVersion: v1
kind: Secret
metadata:
    name: recyclarr-secret
stringData:
    RADARR_API_KEY: ENC[AES256_GCM,data:P2X3EMHxGLzbszFhprP7lv1wuQUFFnRYkCIfWylCzgs=,iv:fRSV7joy2DOU7otB0UyEvtCg0UEKMsIdY+6j04yS/DA=,tag:+T98runl4O6SvgMgsaur0A==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:bt1WEtco9OR12T4y20tF99YS5Q2D2UMSiZ0HUqjkpbc=,iv:VBf/2kY1+S1pe6N+0f3f2a1eiiyYtJYaIlHIukpXUxs=,tag:IQxZJsKTLxYxWT3PkeU/JQ==,type:str]
sops:
    age:
        - recipient: age1scuvt8def4hy9nxckwjty642tg2c0vj47svgtmsvqk5xu4055fgq2k6c4a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmczJ4YzNUdm1MNmlGR2d3
            UEhWdTJLT1dlZHpNUmFldEc1VFNTTm53bXhNCkNmbjNBcENwMzVGQTBIVzBncGVv
            ZmhDbmdEOWtMZ1I1TU8rOEdGT2E3TmMKLS0tIE9DMjIzWGw2ei8vb2tsaW83dkJq
            dk1kV09tWHJJWDlwUXB0bWtFUFlZMGcKAVrxAXOif/hQ+ZBlKZ3VXq03IHQZcyzx
            QRykDc7Kx/V3SUdL1wt2fhXaedxdXaUpCIxrOjOOmJLl25SARTwxxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-08T13:21:45Z"
    mac: ENC[AES256_GCM,data:7diHR1ete1dG2rrvOD+z0fV14B4p3kWZCjQ8UjNyTAOuxvt62fZ9WAIk3EydIo5oKZttOcop6YQqncLgZpGqTkNGpiPftmBO0RAa9YTxDxFPoESLFQSs/60Xw5a+pyEs+a/ijuzqlTrc+I4SESooMHazgUoRG+QOn/J47ifoqVA=,iv:htZhLtKwZax6j8bQmVDJgmjEF7lFzgSGtw5sO5D8rtU=,tag:tTMeYFEHPhNPu/qdmK33Tw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
